infer:
  pose2d:
  pose3d:  
  pose2d_weights:
  pose3d_weights:
  device: 
  det_model:
  det_weights:
  det_cat_ids:
input:
  path: 'input path'
output:
  draw_heatmap: 
  out_dir: 'output'
#   vis_out_dir:
#   pred_out_dir:
#   out_dir:
show: True